on:
  push:
    branches: [main]

name: blogdown

jobs:
  blogdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Install blogdown
        run: |
          R -e 'install.packages("blogdown")'
      - name: Install hugo
        run: |
          R -e 'blogdown::install_hugo(version = "0.92.1")'
      - name: Install devtools
        run: |
          R -e 'install.packages("devtools")'
      - name: Install cwebby
        run: |
          R -e 'devtools::install()'
      - name: Build site
        run: |
          R -e 'blogdown::build_site(local = TRUE)'
      - name: s3Sync
        uses: Morr0/s3Sync@v.0.1
        with:
          # AWS Access ID
          accessKey: ${{ secrets.AWS_ACCESS_KEY }}
          # AWS SECRET Key
          secretKey: ${{ secrets.AWS_SECRET_KEY }}
          # AWS Region
          region: ap-southeast-2
          # AWS Bucket name
          bucket: s3://callumwebby.com/  
          # Directory of github to sync, use '.' for the entire repository
          dir: public
