on:
  push:
    branches: [main]

name: blogdown

jobs:
  blogdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Install blogdown
        run: |
          R -e 'install.packages("blogdown")'
      - name: Install hugo
        run: |
          R -e 'blogdown::install_hugo(version = "0.92.1")'
      - name: Install cwebby
        run: |
          R -e 'devtools::install()'
      - name: Build site
        run: |
          R -e 'blogdown::build_site(local = TRUE)'
